### ISSUE TITLE
How to make the app recognize color schemes and formatters?

### ISSUE THREAD

**Issue by SparksFyz** [apache-superset/superset-ui-plugins#186]
How do I use superset react plugins in vue2?

Hi, I tried to use chart plugin in vue app with vuera. for example, line chart

![image](https://user-images.githubusercontent.com/8748814/63832483-79b0e880-c9a3-11e9-89c4-8158e89376a4.png)

and code example is 

```
<template>
<super-chart chartType="line" width="600" height="600" :formData="chartData" :queryData="queryData"></super-chart>
</template>

chartData: {
bottomMargin: 'auto',
        // colorScheme: 'd3Category10', // no effect
        xAxisFormat: 'smart_date',   // no effect
        colors: [
        '#1f77b4',
        '#ff7f0e',
        '#2ca02c',
        '#d62728',
        '#9467bd',
        '#8c564b',
        '#e377c2',
        '#7f7f7f',
        '#bcbd22',
        '#17becf'
      ],
        leftMargin: 'auto',
        lineInterpolation: 'linear',
        richTooltip: true,
        showBrush: 'auto',
        showLegend: true,
        showMarkers: false,
        vizType: 'line',
        xAxisLabel: '',
        xAxisShowminmax: false,
        xTicksLayout: 'auto',
        yAxisBounds: [
          null,
          null
        ],
        yAxisFormat: '.3s',
        yAxisLabel: '',
        yAxisShowminmax: false,
        yLogScale: false
}
```

but `colorScheme` and  `xAxisFormat`: 'smart_date' take no effect, how do l import or register colorSchema and timeFormat lib?  Thank you

**Comment by kristw** [comment]
You have to register the color schemes and formatters.
In `incubator-superset`, this was done in `setup/setupColors.js` and `setup/setupFormatters.js`

```js
// Colors
import { getCategoricalSchemeRegistry } from '@superset-ui/color';
import categoricalD3 from '@superset-ui/color/esm/colorSchemes/categorical/d3';

categoricalD3.forEach((scheme) => {
  categoricalSchemeRegistry.registerValue(scheme.id, scheme);
});

// Formatters
import { getTimeFormatterRegistry, smartDateFormatter } from '@superset-ui/time-format';

getTimeFormatterRegistry()
  .registerValue('smart_date', smartDateFormatter)
  .setDefaultKey('smart_date');

**Comment by SparksFyz** [comment]
> You have to register the color schemes and formatters.
> In `incubator-superset`, this was done in `setup/setupColors.js` and `setup/setupFormatters.js`
> 
> ```js
> // Colors
> import { getCategoricalSchemeRegistry } from '@superset-ui/color';
> import categoricalD3 from '@superset-ui/color/esm/colorSchemes/categorical/d3';
> 
> categoricalD3.forEach((scheme) => {
>   categoricalSchemeRegistry.registerValue(scheme.id, scheme);
> });
> 
> // Formatters
> import { getTimeFormatterRegistry, smartDateFormatter } from '@superset-ui/time-format';
> 
> getTimeFormatterRegistry()
>   .registerValue('smart_date', smartDateFormatter)
>   .setDefaultKey('smart_date');
> ```

thanks.  I just read register code in `setup` folder~
