### ISSUE TITLE
Installation is failing w/ storybook dependency

### ISSUE THREAD

**Issue by b2kdaman** [apache-superset/superset-ui-plugins#223]
**Describe the bug**
Pulled recent changes and tried to run builds on different envs and got this bug:
```
error Couldn't find package "storybook__addon-knobs@*" required by "@types/storybook__addon-knobs@^5.0.0" on the "npm" registry.
```

**To Reproduce**
Run `yarn install`

**Expected behavior**
Installation should go fine

**Environment (please complete the following information):**
 - superset-ui version: latest/any

**Comment by kristw** [comment]
This should be fixed now.

**Comment by oziniak** [comment]
The issue seem to be still present.
