### ISSUE TITLE
Issue with yarn build command.

### ISSUE THREAD

**Issue by charvigupta** [apache-superset/superset-ui-plugins#272]
I am getting the following error while running yarn build command in  CONTRIBUTING.MD

yarn build
yarn run v1.19.1
$ yarn run build:cjs && yarn run build:esm && yarn run type:dts && yarn run build:assets
$ NODE_ENV=production beemo babel --extensions=".js,.jsx,.ts,.tsx" ./src --out-dir lib/ --delete-dir-on-start --minify --workspaces="@superset-ui/!(demo|generator-superset)"
[1/2] CONFIG Creating config files
[2/2] DRIVER Running Babel v7.7.4 d… (failed)

error: unknown option '--minify'
error: unknown option '--minify'
error: unknown option '--minify'
error: unknown option '--minify'
error: unknown option '--minify'
error: unknown option '--minify'
error: unknown option '--minify'
error: unknown option '--minify'
error: unknown option '--minify'
error: unknown option '--minify'
error: unknown option '--minify'

Failed to execute pipeline. The following errors have occurred:

Command failed with exit code 1: babel --extensions=.js,.jsx,.ts,.tsx ./src --out-dir lib/ --delete-dir-on-start --minify --config-file /home/charvi/Downloads/superset-ui/babel.config.js

Command failed with exit code 1: babel --extensions=.js,.jsx,.ts,.tsx ./src --out-dir lib/ --delete-dir-on-start --minify --config-file /home/charvi/Downloads/superset-ui/babel.config.js

Command failed with exit code 1: babel --extensions=.js,.jsx,.ts,.tsx ./src --out-dir lib/ --delete-dir-on-start --minify --config-file /home/charvi/Downloads/superset-ui/babel.config.js

Command failed with exit code 1: babel --extensions=.js,.jsx,.ts,.tsx ./src --out-dir lib/ --delete-dir-on-start --minify --config-file /home/charvi/Downloads/superset-ui/babel.config.js

Command failed with exit code 1: babel --extensions=.js,.jsx,.ts,.tsx ./src --out-dir lib/ --delete-dir-on-start --minify --config-file /home/charvi/Downloads/superset-ui/babel.config.js

Command failed with exit code 1: babel --extensions=.js,.jsx,.ts,.tsx ./src --out-dir lib/ --delete-dir-on-start --minify --config-file /home/charvi/Downloads/superset-ui/babel.config.js

Command failed with exit code 1: babel --extensions=.js,.jsx,.ts,.tsx ./src --out-dir lib/ --delete-dir-on-start --minify --config-file /home/charvi/Downloads/superset-ui/babel.config.js

Command failed with exit code 1: babel --extensions=.js,.jsx,.ts,.tsx ./src --out-dir lib/ --delete-dir-on-start --minify --config-file /home/charvi/Downloads/superset-ui/babel.config.js

Command failed with exit code 1: babel --extensions=.js,.jsx,.ts,.tsx ./src --out-dir lib/ --delete-dir-on-start --minify --config-file /home/charvi/Downloads/superset-ui/babel.config.js

Command failed with exit code 1: babel --extensions=.js,.jsx,.ts,.tsx ./src --out-dir lib/ --delete-dir-on-start --minify --config-file /home/charvi/Downloads/superset-ui/babel.config.js

Command failed with exit code 1: babel --extensions=.js,.jsx,.ts,.tsx ./src --out-dir lib/ --delete-dir-on-start --minify --config-file /home/charvi/Downloads/superset-ui/babel.config.js
    at ExecuteDriverRoutine.formatAndThrowErrors (/home/charvi/Downloads/superset-ui/node_modules/@beemo/core/lib/routines/RunInWorkspacesRoutine.js:66:15)
    at ExecuteDriverRoutine.execute (/home/charvi/Downloads/superset-ui/node_modules/@beemo/core/lib/routines/RunInWorkspacesRoutine.js:52:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecuteDriverRoutine.run (/home/charvi/Downloads/superset-ui/node_modules/@boost/core/lib/Task.js:156:27)
    at async SerialExecutor.run (/home/charvi/Downloads/superset-ui/node_modules/@boost/core/lib/executors/Serial.js:17:25)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Could you help me out with this? Is the error related to babel or npm ? Or something else?

**Comment by airliquide31** [comment]
Same issue here :(  

Any idea ?

**Comment by kristw** [comment]
Should be fixed in #319
