### ISSUE TITLE
How to use the legacy react plugins?

### ISSUE THREAD

**Issue by madhu-aithal** [apache-superset/superset-ui-plugins#3]
Your question. 
- How do I configure key and register the plugin?

I am importing ChordChartPlugin and configuring it as shown below. Then I am using the plugin with `SuperChart` as mentioned in the README of the plugin [here](https://github.com/apache-superset/superset-ui-plugins/tree/master/packages/superset-ui-legacy-plugin-chart-chord).
```javascript
import ChordChartPlugin from '@superset-ui/legacy-plugin-chart-chord';

new ChordChartPlugin()
            .configure({ key: 'chord' })
            .register();
```

But I am getting the below error in the browser and I am not able to see any chart. Please help me. Am I missing something?
`ERROR chartType="chord" —Error: Item with key "chord" is not registered.`

**Comment by kristw** [comment]
Your code looks right. There is a known issue with multiple copies of `@superset-ui/chart`. Make sure your `node_modules` directory has only one `@superset-ui/chart`. 

1) Try to remove `yarn.lock` or `package-lock.json` and `yarn install` or `npm install` again.
2) If 1) does not work, try deleting `node_modules` directory and try `yarn install` or `npm install` again.

FYI, I am working on a way to avoid this issue or make debug this easier but will take some time until it is released.

**Comment by madhu-aithal** [comment]
@kristw 
I tried both the steps you mentioned and installed the dependencies again, but still I am getting the same error. Also, I have only one version of `@superset-ui/chart` in `node_modules`.

**Comment by madhu-aithal** [comment]
Please find below the code where I am using superset plugins. Please let me know if I am missing something. Thanks in advance.

```javascript
import React, { Component } from 'react';
import './App.css';
import { SuperChart } from '../node_modules/@superset-ui/chart/lib';
import ChordChartPlugin from '@superset-ui/legacy-plugin-chart-chord';

new ChordChartPlugin()
    .configure({ key: 'chord' })
    .register();           

class App extends Component {
  render() {
    // new ChordChartPlugin()
    //   .configure({ key: 'chord' })
    //   .register();  
    return (
      <div className="App">
        <div>
            <p> Sample chart</p>        
            <SuperChart
            chartProps={{
              formData: {
                colorScheme: 'd3Category10',
                yAxisFormat: '.2f'
              },
              height: 400,
              payload: {
                data: {
                  matrix: [
                    [ 381, 16, 14, 5, 4, 6 ], 
                    [ 29, 535, 132, 20, 21, 16 ], 
                    [ 22, 18, 1, 3, 0, 214 ], 
                    [ 3, 4, 462, 152, 132, 0 ], 
                    [ 16, 32, 299, 123, 146, 1 ], 
                    [ 22, 83, 53, 21, 22, 6 ]
                  ], nodes: [
                    'Hong Kong', 'Tokyo', 'Taipei', 'Beijing', 'Bangkok', 'Jakarta', 'Singapore'
                  ]
                }
              },
              width: 400
            }}
            chartType="chord"
            className=""
            id=""
            onRenderFailure={function(){}}
            onRenderSuccess={function(){}}
            overrideTransformProps={undefined}
            postTransformProps={function(a){return a}}
            preTransformProps={function(a){return a}}
          />
          </div>
      </div>
    );
  }
}

export default App;
```

**Comment by kristw** [comment]
```js
import { SuperChart } from '@superset-ui/chart';
```

**Comment by madhu-aithal** [comment]
Thanks! It's working now.

**Comment by klazaj** [comment]
@madhu-aithal which file did you add the `key` and the `Superchart` code?
