### ISSUE TITLE
beemo.config module not found to build

### ISSUE THREAD

**Issue by kalimuthu123** [apache-superset/superset-ui-plugins#320]
![beemo](https://user-images.githubusercontent.com/42966797/73642273-6a8f3e80-4697-11ea-8fcb-afb400675436.png)
**Describe the bug**
run built failed
beemo.config module not found

**Expected behavior**
build the ui plugins in the node

**Comment by trepmag** [comment]
@kalimuthu123 try the `kristw--nimbus` branch...

**Comment by kristw** [comment]
Fixed in #319
