### ISSUE TITLE
World Map countries invisible in Ubuntu 18.04 EC2 instance 

### ISSUE THREAD

**Issue by righttracknana** [apache-superset/superset-ui-plugins#413]
**Describe the bug**
Hi, 
I just deployed superset on an AWS EC2 Instance - Ubuntu 18.04 yesterday. Everything is running perfectly fine except I am still experiencing these World map issues (image attached). 

**To Reproduce**
Create an EC2 instance and login into the server using SSH. Installed Ubuntu system dependencies

```
python3 -m venv venv
. venv/bin/activate

pip install apache-superset

superset db upgrade

$ export FLASK_APP=superset
flask fab create-admin

superset load_examples

superset init

fabmanager run --app superset

```
**Expected behavior**
Expected world map to show low country values as an outline but rather they look invisible as per this previous issue https://github.com/apache-superset/superset-ui-plugins/issues/53

**Screenshots**
<img width="1228" alt="Screen Shot 2020-03-27 at 08 19 17" src="https://user-images.githubusercontent.com/56507784/77737514-0ee19180-7006-11ea-9836-b9c6dd0516fb.png">

**Environment (please complete the following information):**
 - superset-ui version: 0.35.2
 - Node version: `node -v` v13.11.0
 - npm version: `npm -v` 6.13.7
 
**Additional context**

For whatever reason when I search for the WorldMap.js in EC2 via SSH I do not get any files as I wanted to make the changes outlined in https://github.com/komoot/superset-ui-plugins/commit/1b6e7d7e434fa65993563cc483848ce4dc5a7205.
All the superset files seem to be in this directory when I search using:
./root/venv/lib/python3.6/site-packages/superset/
but can't seem to find a .js file for the maps. Through GitHub, I found I could use 'npm upgrade' in the /superset/assets folder but there is no package-lock.json file in there for it to run on :/. In addition, this build version does not seem to have the superset-frontend folder.

Any help would be much appreciated.

**Comment by righttracknana** [comment]
Resolved. 

Found the file in `venv/lib/python3.6/site-packages/superset/static/assets/dist/38.a5f0221384b953b482d3.chunk.js` and edited it using the nano editor.

**Comment by raviguptag** [comment]
What is edited and modified in This file 38.a5f0221384b953b482d3.chunk.js.... to make it working?

**Comment by righttracknana** [comment]
> What is edited and modified in This file 38.a5f0221384b953b482d3.chunk.js.... to make it working?

I edited it as per the recommendations in this link:
https://github.com/komoot/superset-ui-plugins/commit/1b6e7d7e434fa65993563cc483848ce4dc5a7205
